config/routes.rb
Rails.application.routes.draw do
  resources :servicios

  resources :clientes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
    validates :nombre, :apellido, :email, presence: true
    validates :email, email: true, uniqueness: true

    def to_s
        "#{nombre} #{apellido}"
    end

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  belongs_to :cliente
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base

    protected

    def permitted_params
        params.permit(:cliente => [:nombre, :apellido, :email])
    end
end

app/controllers/servicios_controller.rb
class ServiciosController < InheritedResources::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :apellido %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.email %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
    <div class="column-10 logo">
        <h1>Nahuel Chaves <small>Clientes</small></h1>
    </div>
    <div class="column-6">
        <nav class="top-nav bg-white nav-responsive">
            <ul class="list-inline">
              <li><%= link_to 'Home', root_path %></li>
              <%= render 'layouts/navigation_links' %>
            </ul>
        </nav>
    </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="True">
    <title><%= content_for?(:title) ? yield(:title) : "Clientes" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Clientes" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container align-center">
      <!--<header>-->
        <%= render 'layouts/navigation' %>
      <!--</header>-->
      <main role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="True">
    <title><%= content_for?(:title) ? yield(:title) : "Clientes" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Clientes" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row"></div>
    </div>
    <div class="login-container fondo-oscuro">
      <div class="container align-center">
        <div class="row">
          <div class="column-6 push-5">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
          alert(Modernizr.input.placeholder);
        });

        Modernizr.load({
            test: Modernizr.input.placeholder,
            nope: [
                    <%= asset_path('polyfills/placeholder.css') %>,
                    <%= asset_path('polyfills/placeholder.jquery.js') %>, // this and the css above are the only required files
                  ]
        });

    </script>
  </body>
</html>

app/views/servicios/_form.html.erb
<%= simple_form_for(@servicio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :cliente %>
    <%= f.input :alta %>
    <%= f.input :baja %>
    <%= f.input :user %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editing servicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @servicio %> |
<%= link_to 'Back', servicios_path %>

app/views/servicios/index.html.erb
<h1>Listing servicios</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Alta</th>
      <th>Baja</th>
      <th>User</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.cliente %></td>
        <td><%= servicio.alta %></td>
        <td><%= servicio.baja %></td>
        <td><%= servicio.user %></td>
        <td><%= servicio.password %></td>
        <td><%= link_to 'Show', servicio %></td>
        <td><%= link_to 'Edit', edit_servicio_path(servicio) %></td>
        <td><%= link_to 'Destroy', servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @servicio.cliente %>
</p>

<p>
  <strong>Alta:</strong>
  <%= @servicio.alta %>
</p>

<p>
  <strong>Baja:</strong>
  <%= @servicio.baja %>
</p>

<p>
  <strong>User:</strong>
  <%= @servicio.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @servicio.password %>
</p>

<%= link_to 'Edit', edit_servicio_path(@servicio) %> |
<%= link_to 'Back', servicios_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>